// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '', // my api key
    appId: '1:41520065615:web:70532b865b8fe124face3a',
    messagingSenderId: '41520065615',
    projectId: 'plantopia-acced',
    authDomain: 'plantopia-acced.firebaseapp.com',
    storageBucket: 'plantopia-acced.appspot.com',
    measurementId: 'G-JJKCKJXX64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '', // my api key
    appId: '1:41520065615:android:7063a9b9c5b5a85dface3a',
    messagingSenderId: '41520065615',
    projectId: 'plantopia-acced',
    storageBucket: 'plantopia-acced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '', // my api key
    appId: '1:41520065615:ios:94713bdee6e6aaebface3a',
    messagingSenderId: '41520065615',
    projectId: 'plantopia-acced',
    storageBucket: 'plantopia-acced.appspot.com',
    iosBundleId: 'com.example.plantopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '', // my api key
    appId: '1:41520065615:ios:94713bdee6e6aaebface3a',
    messagingSenderId: '41520065615',
    projectId: 'plantopia-acced',
    storageBucket: 'plantopia-acced.appspot.com',
    iosBundleId: 'com.example.plantopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '', // my api key
    appId: '1:41520065615:web:3666e11224d62136face3a',
    messagingSenderId: '41520065615',
    projectId: 'plantopia-acced',
    authDomain: 'plantopia-acced.firebaseapp.com',
    storageBucket: 'plantopia-acced.appspot.com',
    measurementId: 'G-9VC8XRS7KL',
  );
}
